seasonmanager/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'seasonmanager.views.home', name='home'),
    # url(r'^seasonmanager/', include('seasonmanager.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^seasonplanner/', include('seasonplanner.urls', namespace='seasonplanner', app_name='seasonplanner')),
)

seasonplanner/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView
from seasonplanner.models import Season, Week

from seasonplanner import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^seasons/$', views.seasons, name='seasons'),
    url(r'^seasons/(?P<pk>\d+)/$',
        views.SeasonDetail.as_view(), name='detail'),
    url(r'^seasons/create/$', views.create, name='create'),
    url(r'^weeks/(?P<pk>\d+)/$',
        views.WeekDetailView.as_view(), name='week_detail'),
    url(r'^workouts/create/$',
        views.workout_create, name='workout_create'),
)

seasonplanner/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, timedelta

# Create your models here.

class Season(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    def __str__(self):
        return self.name
    def number_of_weeks(self):
        return self.week_set.count()

class Goal(models.Model):
    """Parent Class for defining goals at a variety of levels"""
    text = models.CharField(max_length=200)
    completed = models.BooleanField()
    def __str__(self):
        return self.text
    
    class Meta:
        abstract = True

class SeasonGoal(Goal):
    season = models.ForeignKey(Season)
    
#class PhysicalAttribute(models.Model):
#    attribute_name = models.CharField(max_length=100)
#    description = models.CharField(max_length=200)
#
#    def __str__(self):
#        return self.attribute_name + " - " + self.description    

class Week(models.Model):
    """Week class defines each week of the training season"""
    season = models.ForeignKey(Season)
    start_date = models.DateField()
    description = models.CharField(max_length=100)
    def weekrange(self):
        d1 = self.start_date
        d2 = d1 + timedelta(days=7)
        return d1.strftime("%m/%d/%Y") + "-" + d2.strftime("%m/%d/%Y")
    def __str__(self):
        return self.description + ": " + self.weekrange()
    def planned_hours(self):
        s = self.plannedworkout_set.aggregate(models.Sum('workout_length'))
        if s['workout_length__sum'] is None:
            s['workout_length__sum'] = 0
        return s['workout_length__sum']
    
    def completed_hours(self):
        s = self.completedworkout_set.aggregate(models.Sum('workout_length'))
        if s['workout_length__sum'] is None:
            s['workout_length__sum'] = 0
        return s['workout_length__sum']
    
#    physical_attributes = models.ManyToManyField(PhysicalAttribute, verbose_name="list of attributes")
            
class Workout (models.Model):
    week = models.ForeignKey(Week)
    workout_date = models.DateField()
    workout_length = models.IntegerField("Workout Length (minutes)")
    notes = models.TextField()
    def __str__(self):
        return self.workout_date.strftime("%m/%d/%Y") + " - " + str(self.workout_length) + " minutes"
    class Meta:
        abstract = True

class CompletedWorkout(Workout):
    """An implementation of the Workout parent class for tracking completed workouts"""

class PlannedWorkout(Workout):
    """An implementation of the Workout parent class for tracking planned workouts"""
    
    
    

seasonplanner/forms.py
from datetime import date
from django import forms
from seasonplanner.models import Workout

class SeasonForm(forms.Form):
    name = forms.CharField(label="Season Name", max_length=200)
    start = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}),label="Start Date", initial= date.today())
    length= forms.IntegerField(widget=forms.TextInput(attrs={'type':'number','min':4,'max':52,'step':1}),label="Number of Weeks")

class WorkoutForm(forms.Form):
    COMPLETED = 'COMPLETED'
    PLANNED = 'PLANNED'
    STATUS_CHOICES = (
        (COMPLETED, 'Completed'),
        (PLANNED, 'Planned'),
    )
    status = forms.ChoiceField(label="Status", choices=STATUS_CHOICES)
    workout_date = forms.DateField(required=True,widget=forms.DateInput(attrs={'type':'date'}),label="Workout Date") 
    workout_length = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'type':'number','step':1}), label="Length")
    notes = forms.CharField(label="Notes", required=False)

seasonplanner/views.py
#Create your views here.

from datetime import date, timedelta

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate
from django.views.generic import DetailView

from seasonplanner.models import Season, Week, SeasonGoal, Workout, CompletedWorkout, PlannedWorkout
from seasonplanner.forms import SeasonForm, WorkoutForm

class SeasonDetail(DetailView):

    model = Season
    template_name = 'seasonplanner/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SeasonDetail, self).get_context_data(**kwargs)
        # Add a Queryset of associated weeks
        context['week_list'] = Week.objects.filter(season=context['season'])
        context['goal_list'] = SeasonGoal.objects.filter(season=context['season'])
        return context

def index(request):
    return HttpResponse("Hello, world. You're at the seasonplanner index page.")

def seasons(request):
    season_list = Season.objects.all().order_by('-start_date')
    context = {'season_list': season_list}
    return render(request, 'seasonplanner/seasons.html', context)

def detail(request, season_id):
    season = get_object_or_404(Season, pk=season_id)
    return render(request,'seasonplanner/detail.html', {})
    
def create(request):
    """ Create a new season and the selected number of weeks """
    if request.method == 'POST':
        #Bind the form to the data from the request
        form = SeasonForm(request.POST)
        if form.is_valid(): #All rules have passed
            #Process the request
            new_season = Season()
            # For now this code automatically sets the owner of all Seasons to me
            u = authenticate(username='test', password='test123')
            new_season.owner = u
            new_season.name = form.cleaned_data['name']
            new_season.start_date = form.cleaned_data['start']
            new_season.save()
            d = new_season.start_date
            for i in range(form.cleaned_data['length']):
                new_week = Week()
                new_week.season = new_season
                new_week.description = 'Week ' + str(i+1)
                new_week.start_date = d
                new_week.save()
                d = d + timedelta(days=7)
            
            return HttpResponseRedirect(reverse('seasonplanner:detail', args=(new_season.id,)))
    else:
        form= SeasonForm() # an unbound form

    return render(request,'seasonplanner/create.html', {'form': form, })

class WeekDetailView(DetailView):
    model = Week
    template_name = 'seasonplanner/week_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(WeekDetailView, self).get_context_data(**kwargs)
        # Add a Queryset of associated workouts
        context['planned_workout_list'] = PlannedWorkout.objects.filter(week=context['week'])
        context['completed_workout_list'] = CompletedWorkout.objects.filter(week=context['week'])
        return context

def workout_create(request):
    """
    Create a new Workout (either planned or completed) associated with a
    given week
    """
    if request.method == 'POST':
        #Bind the form to the data from the request
        form = WorkoutForm(request.POST)
        if form.is_valid(): # All rules have passed
            # Process the request
            if form.cleaned_data['status'] == 'COMPLETED':
                w = CompletedWorkout()
            else:
                w = PlannedWorkout()
            w.week = Week.objects.get(description = 'Week 1')
            w.workout_date = form.cleaned_data['workout_date']
            w.workout_length = form.cleaned_data['workout_length']
            w.notes = form.cleaned_data['notes']
            w.save()
            return HttpResponseRedirect(reverse('seasonplanner:week_detail', args=(w.week.id,)))

    else:
        form = WorkoutForm() # an unbound form

    return render(request, 'seasonplanner/workout_create.html', {'form': form, })

seasonplanner/templates/seasonplanner/base.html
<!DOCTYPE html>

<html>
    <head>        
        <title>{% block title %}Season Planner{% endblock %}</title>
    </head>
    
    <body>
        <header>
            {% block header %}{% endblock %}
        </header>


        <section>
            {% block content %}{% endblock %}
        </section>

    </body>
</html>    

seasonplanner/templates/seasonplanner/create.html
{% extends 'seasonplanner/base.html' %}

{% block title %}Create a new season{% endblock %}

{% block header %}<h1>Create a new season</h1>{% endblock %}

{% block content %}        
            <form action="{% url 'seasonplanner:create' %}" method="post">
            {% csrf_token %}
                {{ form.as_ul }}
            <input type="submit" value="Create" id="Create">
            </form>
{% endblock %}

seasonplanner/templates/seasonplanner/detail.html
{% extends 'seasonplanner/base.html' %}

{% block title %}Season Detail{% endblock %}

{% block header %}<h1>{{ season.name}}</h1>{% endblock %}

{% block content %}
    <p>Start Date: {{ season.start_date }}</p>
    <p>Length of Season (weeks): {{ season.number_of_weeks }}</p>
    <p>
    {% if goal_list %}
    <ul>
    {% for goal in goal_list %}
        <li>{{ goal }}</li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No goals are defined for this Season.</p>
    {% endif %}
    </p>
    <p>
    {% if week_list %}
    <ul>
    {% for week in week_list %}
        <li><a href="{% url 'seasonplanner:week_detail' week.id %}">{{ week }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No weeks are defined for this Season.</p>
    {% endif %}
    </p>
{% endblock %}

seasonplanner/templates/seasonplanner/seasons.html
{% if season_list %}
    <ul>
    {% for season in season_list %}
        <li><a href="{% url 'seasonplanner:detail' season.id %}">{{ season.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>You do not have any seasons defined. Create a season.</p>
{% endif %}

<a href="{% url 'seasonplanner:create' %}">Create a new Season</a>

seasonplanner/templates/seasonplanner/week_detail.html
{% extends 'seasonplanner/base.html' %}

{% block title %}Week Detail{% endblock %}

{% block header %}<h1>Week Detail</h1>{% endblock %}

{% block content %}
    <p>Season: {{ week.season.name }}</p>
    <p>Week Start Date: {{ week.start_date }}</p>
    <p>Description: {{ week.description }}</p>
    {% include "seasonplanner/simple_list.html" with simplelist=planned_workout_list  header="Planned Workouts" %}    
    <p>Planned Hours: {{ week.planned_hours }}</p>
    {% include "seasonplanner/simple_list.html" with simplelist=completed_workout_list  header="Completed Workouts" %}    
    <p>Completed Hours: {{ week.completed_hours }}</p>
    <p><a href="{% url 'seasonplanner:workout_create' %}">Add a workout</a>
{% endblock %}